package prestamo;

import javax.swing.*;
import java.awt.event.*;
import java.sql.*;
import CONEXION.CONEXION;

public class CREAR_RECURSOS extends javax.swing.JFrame {

    public CREAR_RECURSOS() {
        initComponents();
        
    }

    private void crearRecurso() {
    // Obtener los valores del formulario
    String colorTexto = color.getText().trim();
    String marcaTexto = marca.getText().trim();
    String inventarioTexto = inventario.getText().trim();
    String estadoTexto = estado.getSelectedItem().toString();
    String descripcionTexto = descripcion.getText().trim();
    String tipoRecursoTexto = tipo_recurso.getText().trim(); 

    // Validar campos obligatorios
    if (colorTexto.isEmpty() || marcaTexto.isEmpty() || inventarioTexto.isEmpty() ||
            estadoTexto.equals("SELECCIONE") || descripcionTexto.isEmpty()) {
        JOptionPane.showMessageDialog(this, "❌ Todos los campos son obligatorios.");
        return;
    }

    // Verificar que el campo inventario sea numérico
    try {
        Integer.parseInt(inventarioTexto);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "❌ El campo 'Inventario' debe ser un número.");
        return;
    }

    try (Connection conn = CONEXION.conectar()) {
        // Consulta SQL para insertar un nuevo equipo (sin la columna ID_EQUIPO)
        String sql = "INSERT INTO EQUIPO (INVENTARIO, COLOR, MARCA, ESTADO, DESCRIPCION,TIPO_RECURSO) " +
                     "VALUES (?, ?, ?, ?, ?, ?)";

        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setInt(1, Integer.parseInt(inventarioTexto));   // INVENTARIO
            stmt.setString(2, colorTexto);                        // COLOR
            stmt.setString(3, marcaTexto);                        // MARCA
            stmt.setString(4, estadoTexto);                       // ESTADO
            stmt.setString(5, descripcionTexto);                  // DESCRIPCIÓN
            stmt.setString(6, tipoRecursoTexto);                // TIPO_RECURSO
            // Ejecutar la consulta
            int rowsAffected = stmt.executeUpdate();

            // Verificar si se insertó correctamente
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "✅ Recurso creado exitosamente.");
                limpiarCampos(); // Limpiar campos después de la creación
            } else {
                JOptionPane.showMessageDialog(this, "❌ No se pudo crear el recurso.");
            }
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "❌ Error en base de datos: " + e.getMessage());
        e.printStackTrace();
    }
}





    private void limpiarCampos() {
        color.setText("");
        inventario.setText("");
        marca.setText("");
        estado.setSelectedIndex(0);
        descripcion.setText("");
        tipo_recurso.setText("");
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inventario = new javax.swing.JTextField();
        marca = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        estado = new javax.swing.JComboBox<>();
        cancelar = new javax.swing.JButton();
        crear = new javax.swing.JButton();
        color = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        tipo_recurso = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Creacion de Recursos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 340, 40));

        jLabel1.setBackground(new java.awt.Color(0, 0, 153));
        jLabel1.setToolTipText("");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 90));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel8.setText("Informacion de Recursos");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 370, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Inventario:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Marca:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        inventario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inventario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inventarioKeyTyped(evt);
            }
        });
        jPanel1.add(inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 210, 40));

        marca.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        marca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                marcaKeyTyped(evt);
            }
        });
        jPanel1.add(marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 210, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Descripcion:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, -1, -1));

        estado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "ACTIVO", "INACTIVO" }));
        jPanel1.add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 210, 40));

        cancelar.setBackground(new java.awt.Color(0, 0, 0));
        cancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelar.setForeground(new java.awt.Color(255, 255, 255));
        cancelar.setText("CANCELAR");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 650, 160, 50));

        crear.setBackground(new java.awt.Color(0, 0, 0));
        crear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        crear.setForeground(new java.awt.Color(255, 255, 255));
        crear.setText("CREAR");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });
        jPanel1.add(crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 650, 160, 50));

        color.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });
        color.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                colorKeyTyped(evt);
            }
        });
        jPanel1.add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 210, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Color:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        descripcion.setColumns(20);
        descripcion.setRows(5);
        jScrollPane1.setViewportView(descripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 490, 80));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Estado:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));

        tipo_recurso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tipo_recurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_recursoActionPerformed(evt);
            }
        });
        tipo_recurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tipo_recursoKeyTyped(evt);
            }
        });
        jPanel1.add(tipo_recurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 210, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Tipo de recurso:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed

        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed

        crearRecurso();
     // TODO add your handling code here:
    }//GEN-LAST:event_crearActionPerformed

    private void inventarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inventarioKeyTyped
        char c = evt.getKeyChar();
        // Aceptar solo letras mayúsculas y espacios
        if (inventario.getText().length ()>=30) 
                evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_inventarioKeyTyped

    private void marcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_marcaKeyTyped
        char c = evt.getKeyChar();
        // Aceptar solo letras mayúsculas y espacios
        if (marca.getText().length ()>=30) 
                evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_marcaKeyTyped

    private void colorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_colorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_colorKeyTyped

    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorActionPerformed

    private void tipo_recursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_recursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_recursoActionPerformed

    private void tipo_recursoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tipo_recursoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_recursoKeyTyped
    

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField color;
    private javax.swing.JButton crear;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JComboBox<String> estado;
    private javax.swing.JTextField inventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField tipo_recurso;
    // End of variables declaration//GEN-END:variables
}
