package prestamo;

import javax.swing.*;
import java.awt.event.*;
import java.sql.*;
import CONEXION.CONEXION; // Asegúrate de importar correctamente tu clase de conexión

public class CREAR_USUARIOS extends javax.swing.JFrame  {

    public CREAR_USUARIOS() {
        initComponents();
    }

    private void crearUsuario() {
        // Obtener los valores del formulario
        String documento = cedula.getText().trim();
        String nombres = nombre.getText().trim();
        String apellidos = apellido.getText().trim();
        String correoTexto = correo.getText().trim();
        String telefonoTexto = telefono.getText().trim();
        String rol = tipo_usuario.getSelectedItem().toString();
        String campusSeleccionado = campus.getSelectedItem().toString();
        String contrasena = new String(contraseña.getPassword()); // Para obtener el texto del JPasswordField
        java.sql.Date fechaNacimiento = new java.sql.Date(fecha_nac.getDate().getTime());
        java.sql.Date fechaExpiracion = new java.sql.Date(fecha_exp.getDate().getTime());

        // Validación de los campos
        if (documento.isEmpty() || nombres.isEmpty() || apellidos.isEmpty() || correoTexto.isEmpty() || 
            telefonoTexto.isEmpty() || contrasena.isEmpty() || rol.equals("SELECCIONE") || campusSeleccionado.equals("SELECCIONE")) {
            JOptionPane.showMessageDialog(this, "Por favor completa todos los campos.");
            return;
        }

        try (Connection conn = CONEXION.conectar()) {
            // Consulta SQL para insertar un nuevo usuario
            String sql = "INSERT INTO usuarios (cedula, nombre, apellido, correo, telefono, tipo_usuario, campus, " +
                         "contraseña, fecha_nac, fecha_exp, estado) " +
                         "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

            PreparedStatement stmt = conn.prepareStatement(sql);

            // Establecer los parámetros en la consulta SQL
            stmt.setString(1, documento); // Cedula
            stmt.setString(2, nombres);   // Nombre
            stmt.setString(3, apellidos); // Apellido
            stmt.setString(4, correoTexto); // Correo
            stmt.setString(5, telefonoTexto);  // Telefono
            stmt.setString(6, rol);       // Tipo de usuario (rol)
            stmt.setString(7, campusSeleccionado); // Campus
            stmt.setString(8, contrasena); // Contraseña
            stmt.setDate(9, fechaNacimiento); // Fecha de nacimiento
            stmt.setDate(10, fechaExpiracion); // Fecha de expiración
            stmt.setString(11, "ACTIVO");  // Estado del usuario (ACTIVO)

            // Ejecutar la consulta
            int resultado = stmt.executeUpdate();

            // Verificar si la operación fue exitosa
            if (resultado > 0) {
                JOptionPane.showMessageDialog(this, "✅ Usuario creado exitosamente.");
                limpiarCampos(); // Limpiar campos después de la creación
            } else {
                JOptionPane.showMessageDialog(this, "❌ No se pudo crear el usuario.");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "❌ Error en base de datos: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void limpiarCampos() {
        cedula.setText("");
        nombre.setText("");
        apellido.setText("");
        correo.setText("");
        telefono.setText("");
        contraseña.setText("");
        tipo_usuario.setSelectedIndex(0); // Resetear JComboBox tipo_usuario
        campus.setSelectedIndex(0); // Resetear JComboBox campus
        fecha_nac.setDate(null); // Limpiar fecha de nacimiento
        fecha_exp.setDate(null); // Limpiar fecha de expiración
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tipo_usuario = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        crear = new javax.swing.JButton();
        cedula = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        campus = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        fecha_nac = new com.toedter.calendar.JDateChooser();
        fecha_exp = new com.toedter.calendar.JDateChooser();
        telefono = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        contraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Creacion de usuarios");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 340, 40));

        jLabel1.setBackground(new java.awt.Color(0, 0, 153));
        jLabel1.setToolTipText("");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 90));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel8.setText("Informacion Personal");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 320, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Nombres:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Apellidos:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        nombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
        });
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 210, 40));

        apellido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidoKeyTyped(evt);
            }
        });
        jPanel1.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 210, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Tipo de Usuario:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, -1, -1));

        tipo_usuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tipo_usuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "DOCENTE", "ADMINISTRATIVO", "ADMINISTRADOR" }));
        jPanel1.add(tipo_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 210, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Campus:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, -1, -1));

        cancelar.setBackground(new java.awt.Color(0, 0, 0));
        cancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelar.setForeground(new java.awt.Color(255, 255, 255));
        cancelar.setText("CANCELAR");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 650, 160, 50));

        crear.setBackground(new java.awt.Color(0, 0, 0));
        crear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        crear.setForeground(new java.awt.Color(255, 255, 255));
        crear.setText("CREAR");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });
        jPanel1.add(crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 650, 160, 50));

        cedula.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cedulaKeyTyped(evt);
            }
        });
        jPanel1.add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 210, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Cedula:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        correo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                correoKeyTyped(evt);
            }
        });
        jPanel1.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 210, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Correo:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, -1));

        campus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "BUCARAMANGA", "SAN GIL", "BARRANCABERMEJA", "BOGOTA" }));
        jPanel1.add(campus, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 210, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Fecha de expedicion:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Fecha de nacimiento:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));
        jPanel1.add(fecha_nac, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 210, 40));
        jPanel1.add(fecha_exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 210, 40));

        telefono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoKeyTyped(evt);
            }
        });
        jPanel1.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 210, 40));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Telefono:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Contraseña:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, -1, -1));
        jPanel1.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 590, 210, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed

        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
       crearUsuario(); // TODO add your handling code here:
    }//GEN-LAST:event_crearActionPerformed

    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
        char c = evt.getKeyChar();
        // Aceptar solo letras mayúsculas y espacios
        if (nombre.getText().length ()>=30) 
                evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_nombreKeyTyped

    private void apellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoKeyTyped
        char c = evt.getKeyChar();
        // Aceptar solo letras mayúsculas y espacios
        if (apellido.getText().length ()>=30) 
                evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoKeyTyped

    private void cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cedulaKeyTyped
        char c = evt.getKeyChar();
        // Aceptar solo letras mayúsculas y espacios
        if (cedula.getText().length ()>=10) 
                evt.consume();  
                if (c<'0' || c>'9') evt.consume();// TODO add your handling code here:
    }//GEN-LAST:event_cedulaKeyTyped

    private void correoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_correoKeyTyped
    char c = evt.getKeyChar();
        // Aceptar solo letras mayúsculas y espacios
        if (correo.getText().length ()>=30) 
                evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_correoKeyTyped

    private void telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoKeyTyped
    

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.JComboBox<String> campus;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField cedula;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JTextField correo;
    private javax.swing.JButton crear;
    private com.toedter.calendar.JDateChooser fecha_exp;
    private com.toedter.calendar.JDateChooser fecha_nac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField telefono;
    private javax.swing.JComboBox<String> tipo_usuario;
    // End of variables declaration//GEN-END:variables
}
