package prestamo;

import javax.swing.*;
import java.awt.*;

public class PERFIL extends JPanel {

    public PERFIL() {
        initComponents(); // Llama a la inicialización de los componentes
        setPreferredSize(new Dimension(980, 710)); // Ajusta según necesidades
        
    }
// En la clase PERFIL
public void setDatosUsuario(String nombreUsuario, String correoUsuario) {
        nombre.setText(nombreUsuario);
        correo.setText(correoUsuario);
        
        // Asegurar que el texto sea visible (blanco sobre fondo oscuro)
        nombre.setForeground(Color.WHITE);
        correo.setForeground(Color.WHITE);
        
        // Actualizar la visualización
        nombre.revalidate();
        nombre.repaint();
        correo.revalidate();
        correo.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        correo = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        con_guardar = new javax.swing.JButton();
        con_nueva = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        con_actual = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        u_guardar1 = new javax.swing.JButton();
        campus = new javax.swing.JComboBox<>();
        u_correo = new javax.swing.JTextField();
        u_nombre = new javax.swing.JTextField();
        u_apellido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(980, 720));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/perfil 512.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        correo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        correo.setForeground(new java.awt.Color(255, 255, 255));
        correo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        correo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 220, 40));

        nombre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 180, 40));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 710));

        con_guardar.setBackground(new java.awt.Color(0, 0, 0));
        con_guardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        con_guardar.setForeground(new java.awt.Color(255, 255, 255));
        con_guardar.setText("Guardar Cambios");
        con_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con_guardarActionPerformed(evt);
            }
        });
        jPanel1.add(con_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 600, 150, 40));

        con_nueva.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(con_nueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 540, 210, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Nueva Contraseña");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 490, -1, -1));

        con_actual.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(con_actual, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, 210, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Constraseña Actual");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setText("Cambiar Contraseña");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 290, 40));

        u_guardar1.setBackground(new java.awt.Color(0, 0, 0));
        u_guardar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        u_guardar1.setForeground(new java.awt.Color(255, 255, 255));
        u_guardar1.setText("Guardar Cambios");
        u_guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_guardar1ActionPerformed(evt);
            }
        });
        jPanel1.add(u_guardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, 150, 40));

        campus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "BUCARAMANGA", "SAN GIL", "BARRANCABERMEJA", "BOGOTA" }));
        jPanel1.add(campus, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 210, 40));

        u_correo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(u_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 210, 40));

        u_nombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(u_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 210, 40));

        u_apellido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(u_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 210, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Apellido");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Campus");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Correo");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Nombre");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel8.setText("Informacion del Usuario");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 380, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void con_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_con_guardarActionPerformed

    private void u_guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_guardar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_guardar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> campus;
    private javax.swing.JPasswordField con_actual;
    private javax.swing.JButton con_guardar;
    private javax.swing.JPasswordField con_nueva;
    private javax.swing.JLabel correo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField u_apellido;
    private javax.swing.JTextField u_correo;
    private javax.swing.JButton u_guardar1;
    private javax.swing.JTextField u_nombre;
    // End of variables declaration//GEN-END:variables
}
